### ISSUE TITLE
This package breaks core-cancel action.

### ISSUE THREAD

**Issue by redfellow** [crot4lus/project-dropdown#1]
With `project-dropdown` enabled, hitting `ESC` to close the find & replace dialog or `CTRL-P` dialog no longer works at all. Tested disabling the package and they work again.

Edit: OS:  Ubuntu 14.04, Atom 1.2.2.

**Comment by GlennTaylorDigital** [comment]
Hi, this doesn't seem to be an issue on my machine - could you try the latest version and let me know if the issue persists.
