### ISSUE TITLE
Frequent need to disable/enable addon to make it work

### ISSUE THREAD

**Issue by sebet** [crot4lus/project-dropdown#2]
I use the [Project Manager](https://atom.io/packages/project-manager) and each time I open an existing project I need to disable/enable 'Project Dropdown' to make the dropdown work.

Your add-on is very useful but constantly doing this becomes tiresome. Can you take a look at the issue?

Thanks!

**Comment by FezVrasta** [comment]
same problem...

**Comment by GlennTaylorDigital** [comment]
Hi

Apologies, I hadn't been checking the issues often - wasn't aware there was many people using it. Your issues *should* now be resolved, if you still have any issues with it please let me know.

Glenn
