### ISSUE TITLE
Streamline UI

### ISSUE THREAD

**Issue by ProLoser** [crot4lus/project-dropdown#5]
Instead of this: 
![screen shot 2016-08-11 at 12 37 10 pm](https://cloud.githubusercontent.com/assets/67395/17602180/5b3361d0-5fc0-11e6-8c5e-edd6a7411e16.png)

Which takes up a lot of usually unused room, just move the up/down arrow to the right of the project folder row. It would be a small button that you click that expands a drop down (or floating panel for switching)

**Comment by luiguild** [comment]
![captura de tela 2016-11-22 as 15 55 25](https://cloud.githubusercontent.com/assets/16566338/20535544/5823f538-b0cc-11e6-915c-8b63865107d8.png)

😃

**Comment by ProLoser** [comment]
Pretty cool. I'd go so far as to say we don't need the 'Current Project:' text either.

**Comment by GlennTaylorDigital** [comment]
Fixed in #7

**Comment by GlennTaylorDigital** [comment]
@ProLoser I forgot to mention, I've removed the 'Current Project' label and the repeated project name on the folder. This is how it looks now:

![screen shot 2016-11-23 at 15 56 50](https://cloud.githubusercontent.com/assets/1357597/20568776/7fb93c38-b195-11e6-9055-5f7266a85e0b.png)

**Comment by GlennTaylorDigital** [comment]
Thanks for the assistance there @luiguild !

**Comment by ProLoser** [comment]
Awesome!
