### ISSUE TITLE
Project list only shows one project

### ISSUE THREAD

**Issue by timothymarois** [crot4lus/project-dropdown#8]
So far after install ive yet to be able to show many projects in the list. Which I have a lot from the Project Manager, how else can I get this thing to work? Even your image of the mod only shows 1 project.... 

if there is more instructions, there would need to be some type of write-up on how to use this.

**Comment by GlennTaylorDigital** [comment]
More project directories can be added using File -> Add Project Folder within Atom.

I've tested the plugin using Project Manager and it pulls in multiple directories fine, my plugin is also in use on a colleagues machine which also lists multiple directories as expected.
